# File for configuring project / deployment build, push and pull steps

# Generic metadata about this project
name: multi-deployment
prefect-version: 2.11.0

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if
# and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions
# for cloning this project in remote locations
pull:
  - prefect.projects.steps.git_clone_project:
      repository: https://github.com/ravicheetiralatl/actions-prefect-deploy.git
      branch: main
      access_token: "{{ prefect.blocks.secret.github-access-token }}"

deployments:
  - name: Simple_Deployment_1
    description: Simple_Deployment_1
    entrypoint: ./deployment-1/flow1.py:call_api
    parameters: {}
    schedule: null
    tags: []
    version: null
    work_pool:
      job_variables:
        image: prefecthq/prefect:2-latest
      name: simple-pool
      work_queue_name: null
  - name: Simple_Deployment_2
    description: Simple_Deployment_2
    entrypoint: ./deployment-2/flow2.py:call_api
    parameters: {}
    schedule: null
    tags: []
    version: null
    work_pool:
      job_variables:
        image: prefecthq/prefect:2-latest
      name: simple-pool
      work_queue_name: null
