name: Deploy a Prefect flow to Production
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  deploy_flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

# TODO: first run tests then deploy
      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}  # TODO: use OIDC with organisation or enterprise plan.
          prefect-workspace: ${{ secrets.PREFECT_WORKSPACE }}  # TODO: use staging and production workspaces with organisation or enterprise plan.
      - name: Copy Prefect Config
        run: cp ./config/prefect-production.yaml prefect.yaml
      - name: Find requirements.txt
        run: |
          locations=$(find . -type f -name "requirements.txt")
          echo "$locations" > requirements_locations.txt
          cat requirements_locations.txt  
          requirements_locations=$(cat requirements_locations.txt | tr '\n' ',')
          echo $requirements_locations
          echo "REQUIREMENTS_PATHS=$requirements_locations" >> $GITHUB_ENV

      - name: Run Prefect Deploy
        uses: PrefectHQ/actions-prefect-deploy@v3
        with:
            all-deployments: "true"
            requirements-file-paths: ${{ env.REQUIREMENTS_PATHS }}