name: Deploy a Prefect flow to Development
on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'feature/*'
jobs:
  deploy_flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

# TODO: first run tests then deploy
      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}  # TODO: use OIDC with organisation or enterprise plan.
          prefect-workspace: ${{ secrets.PREFECT_WORKSPACE }}  # TODO: use staging and production workspaces with organisation or enterprise plan.
      - name: Copy Prefect Config
        run: cp ./config/prefect-development.yaml prefect.yaml
      - name: Run Prefect Deploy
        uses: PrefectHQ/actions-prefect-deploy@v3
        with:
          #deployment-names: Simple_Deployment_1,Simple_Deployment_2
          all-deployments: "true"
          requirements-file-paths : ./deployment-1/requirements.txt,./deployment-2/requirements.txt
